version: 2.2.4.{build}
skip_tags: false

branches:
  # blacklist gh-pages, since the documentation branch shouldn't be built
  except:
    - gh-pages

environment:
  releaseVersion: 2.2.4
  packageVersion: 2.2.4-pre

assembly_info:
  patch: true
  file: VersionInfo.cs
  assembly_version: "$(releaseVersion)"
  assembly_file_version: "{version}"
  assembly_informational_version: "$(packageVersion)"

nuget:
  account_feed: true

platform: Any CPU

configuration: Release

before_build:
  - nuget restore

build:
  project: CodeOnlyStoredProcedure.sln
  parallel: true
  verbosity: quiet

test:
  assemblies:
    - CodeOnlyTests.dll
    - CodeOnlyTests-NET40.dll

# run smoke tests, and create the nuget package artifacts
after_test:
  - .\SmokeTests\bin\Release\SmokeTests.exe
  - .\SmokeTests-NET40\bin\Release\SmokeTests-NET40.exe
  - ps: nuget pack CodeOnlyStoredProcedures.nuspec -Symbols -NonInteractive -Verbosity detailed -Version $env:packageVersion

artifacts:
  - path: '*.nupkg'

deploy:
  - provider: NuGet
    on:
      branch: master
      appveyor_repo_tag: true   # Now that I'm using github pull requests, only tags should be released to nuget
    api_key:
      secure: YpmJQ9N6F0dfai0xFAoerzB7nruq9NOlhDquhAliwy5cS2A87wU7U+X4Q5eH8vyx
    skip_symbols: false
    artifact: /.*\.nupkg/
